Added a check for Native CC in configure script [CORR]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -365,9 +365,15 @@ if test -n "$sharedir"; then
     uadedatadir="$sharedir"
 fi
 
+$NATIVECC -v 2>/dev/null >/dev/null
+if test "$?" != "0"; then
+    echo Native CC "$NATIVECC" not found, please install a C compiler
+    exit 1
+fi
+
 $TARGETCC -v 2>/dev/null >/dev/null
 if test "$?" != "0"; then
-    echo $TARGETCC not found, please install a C compiler
+    echo Target CC "$TARGETCC" not found, please install a C compiler
     exit 1
 fi
 
